# Generated by Django 3.0.3 on 2020-06-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20200617_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
