# Generated by Django 3.0.3 on 2020-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20200617_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=550)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
