# Generated by Django 3.0.3 on 2020-07-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_auto_20200718_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessages',
            new_name='UserMessage',
        ),
    ]
